# Generated by Django 4.2.7 on 2023-11-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='misamusic',
            name='song_id',
        ),
        migrations.AddField(
            model_name='misamusic',
            name='file_signature',
            field=models.FileField(default='', upload_to='media'),
        ),
        migrations.AddField(
            model_name='misamusic',
            name='song_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='misamusic',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
