# Generated by Django 4.2.7 on 2023-11-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadedfile_remove_misamusic_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misamusic',
            name='song_path',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
